# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentman" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "am"], chdir: "."
    end
  end

  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "df3e418955ec4b90a6af88ba31fcb100707aee5c26ec5410de216421ea2f548d"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c58cf1f1beaaac61109f7b943a054b870b85c6aebd78ece0260124f09d4a80e"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4962aa94f81c8e8f2221ac19cd2bd740e8365daadc335818bbb59ccecc07bef1"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "767bb3564e20c68cae7eba5de2f0e07fe3f775cace94a80a4db3bfc40a7e5ea6"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentman"
  desc "Watch your coding agents from your phone and answer them when they get stuck"
  homepage "https://github.com/lenajeremy/agentman"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "am"

  # No zap stanza required

  caveats <<~EOS
    Get started:

      am install-hooks
      am serve
      am pair

    Then launch agents through the wrapper so you can message them back:

      am claude
      am codex

    `am` uses the public relay by default. It has no transcript database but
    can observe live traffic. To run your own, see
    https://github.com/lenajeremy/agentman/blob/main/docs/self-hosting.md
  EOS
end
