# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentman" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "am"], chdir: "."
    end
  end

  version "0.11.3"

  on_macos do
    on_intel do
      sha256 "8628c01fdc92f8276ef44120d2457722139fae509145de482136b19dd05daa0f"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ff497769e8de3245cd8830bf65e21d4375987bfcce1d95ea6e6f1ead78fa119"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b6add5a433ac0ee7e4a500ca2e2390906bdce617579b8c0c11a42b20727f9dca"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10e9dacfddfa15e379c94ed01b94a3c95445c90efd76a15930ee53ddc775bf3a"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentman"
  desc "Watch your coding agents from your phone and answer them when they get stuck"
  homepage "https://github.com/lenajeremy/agentman"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "am"

  # No zap stanza required

  caveats <<~EOS
    Get started:

      am install-hooks
      am serve
      am pair

    Then launch agents through the wrapper so you can message them back:

      am claude
      am codex

    `am` uses the public relay by default. It has no transcript database but
    can observe live traffic. To run your own, see
    https://github.com/lenajeremy/agentman/blob/main/docs/self-hosting.md
  EOS
end
