# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentman" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "am"], chdir: "."
    end
  end

  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "d7b8ef9246e8745f3851ba479bc3774f996af52d5e5df554d5906515a953832e"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61935069c612223b6065689f57fe50cacadc5b63e2298982224dceca472fc814"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5cb9656e1e9c89988a81a6ad1d4e286e295f978be16f29c4fb90fa1599d7f82"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22af52b4da465733ef6ba8f633e95d34af1c5ed3a4790b5ef46bc60ca651a6b2"
      url "https://github.com/lenajeremy/agentman/releases/download/v#{version}/agentman_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentman"
  desc "Watch your coding agents from your phone and answer them when they get stuck"
  homepage "https://github.com/lenajeremy/agentman"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "am"

  # No zap stanza required

  caveats <<~EOS
    Get started:

      am install-hooks
      am serve
      am pair

    Then launch agents through the wrapper so you can message them back:

      am claude
      am codex

    `am` uses the public relay by default. It has no transcript database but
    can observe live traffic. To run your own, see
    https://github.com/lenajeremy/agentman/blob/main/docs/self-hosting.md
  EOS
end
